name: security audit
on:
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  schedule:
    - cron: '5 4 * * 6'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_protected && github.run_id || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}
permissions:
  contents: read
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - run: cargo install cargo-audit && cargo audit
